FROM alpine:latest

RUN apk add --no-cache nginx nginx-mod-http-brotli

COPY nginx.conf /etc/nginx/http.d/qwasm.conf

RUN mkdir -p /usr/share/nginx/html
COPY dist/ /usr/share/nginx/html/

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]