server {
    listen 8080;
    server_name qwasm-server;
    root /usr/share/nginx/html;

    gzip_static on;
    brotli_static on;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;

    location ~* \.(wasm|js|data|css)$ {
        # Caching headers for static assets
        expires 1y;
        add_header Cache-Control "public, immutable";

        # Important: Re-apply CORP header because inheritance is disabled by the add_header above
        add_header Cross-Origin-Resource-Policy "same-origin" always;
    }

    location / {
        index index.html;
        try_files $uri $uri/ =404;
    }
}